#!/usr/didbs/current/bin/bash
#
# A simple script to create a sandbox for a new package
#
# params: $1=topdir ie. bash
#
. ${BUILDPKG_SCRIPTS}/buildpkg.functions

REQ_DIRS="stage src meta"

topdir=$1
if [ -z "$topdir" ]; then
    error $E_MISSING_ARGS
else
    setdir "$buildpkgbase"
fi

echo "Creating sandbox for $topdir"
${__mkdir} "$topdir"
for i in $REQ_DIRS
do
    ${__mkdir} $topdir/$i
done

${__sed} -e "s;/bin/bash;$__bash;g" $buildpkgscripts/build.sh.template > $topdir/build.sh

${__cp} $buildpkgscripts/pkgdef.template $topdir/meta/pkgdef
${__cp} $buildpkgscripts/relnotes.template $topdir/meta/relnotes
${__cp} $buildpkgscripts/changelog.template $topdir/meta/ChangeLog

# Make build script executable
chmod 755 $topdir/build.sh
